using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SandcastleToDocFx.Sandcastle
{
    public enum ElementType
    {
        None,
        Alert,
        Application,
        AutoOutline,
        Caption,
        Code,
        CodeEntityReference,
        CodeFeaturedElement,
        CodeInline,
        Command,
        Conclusion,
        Content,
        Definition,
        DeveloperConceptualDocument,
        DeveloperGlossaryDocument,
        DeveloperWalkthroughDocument,
        Entry,
        ExternalLink,
        FictitiousUri,
        Glossary,
        GlossaryDiv,
        GlossaryEntry,
        Image,
        Introduction,
        LanguageKeyword,
        LegacyBold,
        LegacyItalic,
        Link,
        LinkText,
        LinkUri,
        List,
        ListItem,
        Literal,
        LocalUri,
        Markup,
        MediaLink,
        NewTerm,
        Para,
        ParameterReference,
        Phrase,
        Placeholder,
        Procedure,
        QuoteInline,
        RelatedTopics,
        Replaceable,
        Row,
        Section,
        Sections,
        Step,
        Steps,
        Summary,
        Superscript,
        Table,
        TableHeader,
        Term,
        Title,
        Token,
        Topic,
        Ui
    }
}
